// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFduxnx4207-dm7xmyk7g3ms1QLXVW3U',
    appId: '1:438744116322:web:68867ad5fe6d92d11d353b',
    messagingSenderId: '438744116322',
    projectId: 'to-do-assignment1',
    authDomain: 'to-do-assignment1.firebaseapp.com',
    storageBucket: 'to-do-assignment1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyU_Es-fRgHUcnP8SMkHwx_STLwG-TBj8',
    appId: '1:438744116322:android:1b5d535a9c366d0e1d353b',
    messagingSenderId: '438744116322',
    projectId: 'to-do-assignment1',
    storageBucket: 'to-do-assignment1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAFduxnx4207-dm7xmyk7g3ms1QLXVW3U',
    appId: '1:438744116322:web:2cecd51c2d4593d91d353b',
    messagingSenderId: '438744116322',
    projectId: 'to-do-assignment1',
    authDomain: 'to-do-assignment1.firebaseapp.com',
    storageBucket: 'to-do-assignment1.firebasestorage.app',
  );
}
